// frontend/src/views/student/StudentDashboard.jsx
import React, { useState, useEffect, useMemo } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext'
import axios from 'axios'

function StudentDashboard() {
  const { user, isAuthenticated } = useAuth()
  const [stats, setStats] = useState([])
  const [profileIncomplete, setProfileIncomplete] = useState(false)
  const [studentProfile, setStudentProfile] = useState({ gwa: '' })
  const [studentActivities, setStudentActivities] = useState([
    { title: 'ICPEP.SE Hackathon' },
    { title: 'Annual JS Summit 2026' },
    { title: 'Campus Clean Drive' }
  ])
  const [studentAwards, setStudentAwards] = useState([
    { title: "Dean's List Awardee", semester: '1st Sem 2025–2026', badge: 'Academic', color: '#f59e0b' },
    { title: 'Best Research Paper', semester: '2nd Sem 2024–2025', badge: 'Research', color: '#3b82f6' },
    { title: 'Outstanding Student Leader', semester: '1st Sem 2024–2025', badge: 'Leadership', color: '#10b981' }
  ])
  const [studentViolations, setStudentViolations] = useState([])
  const [todaySchedule, setTodaySchedule] = useState([])

  const todayLabel = useMemo(() => new Date().toLocaleDateString('en-US', {
    weekday: 'long', month: 'long', day: 'numeric', year: 'numeric'
  }), [])

  const studentChartData = useMemo(() => [
    { sem: "1S'23", gwa: 1.95, pct: 45 }, { sem: "2S'23", gwa: 1.88, pct: 55 },
    { sem: "1S'24", gwa: 1.81, pct: 68 }, { sem: "2S'24", gwa: 1.77, pct: 76 },
    { sem: "1S'25", gwa: 1.74, pct: 83 }, { sem: "2S'25", gwa: 1.72, pct: 90 }
  ], [])

  useEffect(() => {
    const fetchProfile = async () => {
      try {
        const response = await axios.get('http://localhost:8000/api/student/profile')
        const s = response.data
        setProfileIncomplete(!s.gender || !s.contact_number || !s.address)
        setStudentProfile({ ...s })
        setStats(buildStats(s))
      } catch (err) {
        console.error('Failed to fetch student profile:', err)
        setStats(buildStats({}))
      }
    }
    fetchProfile()
  }, [])

  function buildStats(s) {
    return [
      { label: 'My GWA', value: s.gwa || '0.00', delta: 'Academic', deltaClass: 'positive', fill: '80%', iconBg: '#f5f3ff', iconColor: '#8b5cf6', route: '/student/academic-history', iconPath: '<path d="M2 13l3-5 3 3 3-4 5 6H2z" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/>' },
      { label: 'Subjects', value: '7', delta: 'Enrolled', deltaClass: 'positive', fill: '70%', iconBg: '#eff6ff', iconColor: '#3b82f6', route: '/student/schedule', iconPath: '<rect x="2" y="2" width="14" height="14" rx="2" stroke="currentColor" strokeWidth="1.4"/><path d="M6 6h6M6 9h4" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/>' },
      { label: 'Awards', value: '3', delta: 'This year', deltaClass: 'positive', fill: '60%', iconBg: '#fffbeb', iconColor: '#f59e0b', route: '/student/awards', iconPath: '<path d="M9 1.5l1.6 4.8H16l-4.2 3.1 1.6 4.9L9 11.1l-4.4 3.2 1.6-4.9L2 7.3h5.4L9 1.5z" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/>' },
      { label: 'Violations', value: '0', delta: 'Clear', deltaClass: 'positive', fill: '0%', iconBg: '#f0fdf4', iconColor: '#10b981', route: '/student/violations', iconPath: '<circle cx="9" cy="9" r="6" stroke="currentColor" strokeWidth="1.4"/><path d="M6 9l2 2 4-4" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/>' },
      { label: 'Activities', value: '6', delta: 'Non-academic', deltaClass: 'neutral', fill: '50%', iconBg: '#fff5ef', iconColor: '#FF6B1A', route: '/student/activities', iconPath: '<circle cx="9" cy="5" r="3" stroke="currentColor" strokeWidth="1.4"/><path d="M2 16c0-4 3-6 7-6s7 2 7 6" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/>' }
    ]
  }

  return (
    <div className="dashboard-home">
      <div className="hero-banner">
        <div className="ambient ambient-1"></div>
        <div className="ambient ambient-2"></div>
        <div className="ambient ambient-3"></div>

        <div className="hero-body">
          <div className="hero-left">
            <div className="hero-meta">
              <span className="meta-dot"></span>
              <span>AY 2026–2027 · 2nd Semester</span>
            </div>
            <h1 className="hero-heading">
              Good morning, <span className="hero-name">{user?.name?.split(' ')[0] ?? 'Student'}</span> <span className="wave">👋</span>
            </h1>
            <div className="hero-chips">
              <span className="hero-chip">
                <svg viewBox="0 0 16 16" fill="none" style={{width:'12px',height:'12px'}}><circle cx="8" cy="8" r="6" stroke="currentColor" strokeWidth="1.4"/><path d="M8 4.5V8l2.5 1.5" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/></svg>
                {todaySchedule.length} class{todaySchedule.length !== 1 ? 'es' : ''} today
              </span>
            </div>
            <div className="hero-actions">
              <Link to="/student/schedule" className="btn-primary">
                <svg viewBox="0 0 16 16" fill="none" style={{width:'14px',height:'14px'}}>
                  <rect x="1.5" y="2.5" width="13" height="12" rx="2" stroke="currentColor" strokeWidth="1.4"/>
                  <path d="M5 1v3M11 1v3M1.5 6.5h13" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/>
                </svg>
                View Schedule
              </Link>
              <Link to="/student/academic-history" className="btn-ghost">
                <svg viewBox="0 0 16 16" fill="none" style={{width:'13px',height:'13px'}}>
                  <path d="M2 13l3-5 3 3 3-4 5 6H2z" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/>
                </svg>
                Academic History
              </Link>
            </div>
          </div>

          <div className="hero-right">
            <div className="kpi-tile">
              <div className="kpi-tile-header">
                <svg viewBox="0 0 18 18" fill="none" className="kpi-icon">
                  <path d="M2 13l3-5 3 3 3-4 5 6H2z" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/>
                </svg>
                <span className="kpi-eyebrow">Current GWA</span>
              </div>
              <span className="kpi-val">{studentProfile.gwa || '0.00'}</span>
              <span className="kpi-foot">This semester</span>
              <div className="kpi-sparkbar">
                {studentChartData.map((b, i) => (
                  <div key={i} className="kpi-spark-seg" style={{ height: b.pct * 0.28 + 'px', opacity: i === studentChartData.length-1 ? 1 : 0.25 + i*0.1 }}></div>
                ))}
              </div>
            </div>
            <div className="kpi-tile kpi-accent">
              <div className="kpi-tile-header">
                <svg viewBox="0 0 18 18" fill="none" className="kpi-icon">
                  <circle cx="9" cy="5" r="3.5" stroke="currentColor" strokeWidth="1.4"/>
                  <path d="M2 16c0-4 3-6 7-6s7 2 7 6" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/>
                </svg>
                <span className="kpi-eyebrow">Activities</span>
              </div>
              <span className="kpi-val">{studentActivities.length}</span>
              <span className="kpi-foot">Non-academic</span>
              <div className="kpi-ring">
                <svg viewBox="0 0 48 48" fill="none">
                  <circle cx="24" cy="24" r="19" stroke="rgba(255,255,255,0.15)" strokeWidth="5"/>
                  <circle cx="24" cy="24" r="19" stroke="rgba(255,255,255,0.8)" strokeWidth="5" strokeDasharray="119.4" strokeDashoffset="40" strokeLinecap="round" transform="rotate(-90 24 24)"/>
                </svg>
              </div>
            </div>
          </div>
        </div>
      </div>

      {profileIncomplete && (
        <div className="profile-nudge">
          <div className="nudge-bar-right"></div>
          <div className="nudge-left">
            <div className="nudge-icon">
              <svg viewBox="0 0 20 20" fill="none">
                <circle cx="10" cy="7" r="3.5" stroke="currentColor" strokeWidth="1.5"/>
                <path d="M3 17c0-3.5 3-5.5 7-5.5s7 2 7 5.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
              </svg>
            </div>
            <div>
              <p className="nudge-title">Your profile is incomplete</p>
              <p className="nudge-desc">Add your contact details and address to finish registration.</p>
            </div>
          </div>
          <div className="nudge-progress">
            <div className="nudge-steps">
              <div className="nudge-step done"></div>
              <div className="nudge-step done"></div>
              <div className="nudge-step"></div>
              <div className="nudge-step"></div>
            </div>
            <span className="nudge-progress-label">2 of 4 complete</span>
          </div>
          <Link to="/student/profile" className="nudge-cta">Complete Profile →</Link>
        </div>
      )}

      <div className="stats-strip">
        {stats.map((stat, idx) => (
          <div key={idx} className={`stat-chip ${stat.route ? 'stat-chip--clickable' : ''}`} onClick={() => stat.route && window.history.push(stat.route)}>
            <div className="sc-icon" style={{ background: stat.iconBg, color: stat.iconColor }}>
              <svg viewBox="0 0 18 18" fill="none" width="15" height="15" dangerouslySetInnerHTML={{ __html: stat.iconPath }}></svg>
            </div>
            <div className="sc-body">
              <span className="sc-label">{stat.label}</span>
              <span className="sc-value">{stat.value}</span>
            </div>
            <span className={`sc-badge ${stat.deltaClass}`}>{stat.delta}</span>
            <div className="sc-progress">
              <div className="sc-progress-fill" style={{ width: stat.fill, background: stat.iconColor }}></div>
            </div>
          </div>
        ))}
      </div>

      <div className="bottom-grid">
        <div className="panel">
          <div className="panel-header">
            <div>
              <h3 className="panel-title">Today's Schedule</h3>
              <p className="panel-sub">{todayLabel}</p>
            </div>
            <Link to="/student/schedule" className="panel-link">View all →</Link>
          </div>
          <div className="timeline">
            {todaySchedule.length === 0 ? (
              <div className="empty-state">
                <svg viewBox="0 0 24 24" fill="none" style={{width:'28px',height:'28px',opacity:'.25'}}>
                  <rect x="3" y="4" width="18" height="17" rx="3" stroke="currentColor" strokeWidth="1.4"/>
                  <path d="M8 2v4M16 2v4M3 9h18" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/>
                </svg>
                <span>No classes today</span>
              </div>
            ) : (
              todaySchedule.map((cls, idx) => (
                <div key={idx} className="tl-item">
                  <div className="tl-time">
                    <span className="tl-t">{cls.time}</span>
                    <span className="tl-dur">{cls.duration}</span>
                  </div>
                  <div className="tl-track">
                    <div className="tl-node" style={{ background: cls.color }}></div>
                    {idx < todaySchedule.length - 1 && <div className="tl-rail"></div>}
                  </div>
                  <div className="tl-content">
                    <p className="tl-subject">{cls.subject}</p>
                    <p className="tl-meta">{cls.professor} · {cls.room}</p>
                    <span className="tl-badge" style={{ background: cls.color + '18', color: cls.color }}>{cls.type}</span>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>

        <div className="panel">
          <div className="panel-header">
            <div>
              <h3 className="panel-title">Awards & Recognition</h3>
              <p className="panel-sub">Your achievements this year</p>
            </div>
            <Link to="/student/awards" className="panel-link">View all →</Link>
          </div>
          <div className="awards-list">
            {studentAwards.slice(0,3).map((award, idx) => (
              <div key={idx} className="award-row">
                <div className="award-icon" style={{ background: award.color + '18', color: award.color }}>
                  <svg viewBox="0 0 14 14" fill="none" style={{width:'13px',height:'13px'}}>
                    <path d="M7 1l1.5 4H13l-3.5 2.5 1.5 4L7 9.5 3.5 12l1.5-4L1 5h4.5L7 1z" stroke="currentColor" strokeWidth="1.2" strokeLinejoin="round"/>
                  </svg>
                </div>
                <div className="award-body">
                  <p className="award-title">{award.title}</p>
                  <p className="award-sem">{award.semester}</p>
                </div>
                <span className="award-chip">{award.badge}</span>
              </div>
            ))}
            {studentAwards.length === 0 && <div className="empty-state"><span>No awards yet</span></div>}
          </div>

          <div className="divider"></div>

          <div className="viol-section">
            <div className="viol-header">
              <span className="viol-label">Violations</span>
              <Link to="/student/violations" className="panel-link">See all →</Link>
            </div>
            {studentViolations.length === 0 ? (
              <div className="viol-clear">
                <div className="viol-check">
                  <svg viewBox="0 0 12 12" fill="none" style={{width:'10px',height:'10px'}}>
                    <path d="M2 6l3 3 5-5" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                </div>
                <span>No active violations — keep it up!</span>
              </div>
            ) : null}
          </div>
        </div>

        <div className="panel">
          <div className="panel-header">
            <div>
              <h3 className="panel-title">Academic Performance</h3>
              <p className="panel-sub">GWA trend per semester</p>
            </div>
            <Link to="/student/academic-history" className="panel-link">History →</Link>
          </div>
          <div className="chart-area">
            {studentChartData.map((bar, i) => (
              <div key={i} className="chart-col">
                <div className="chart-col-inner">
                  <div className={`chart-bar ${i === studentChartData.length - 1 ? 'chart-bar--active' : ''}`} style={{ height: bar.pct + '%' }}>
                    <div className="chart-tip">{bar.sem}<br><strong>{bar.gwa}</strong></div>
                  </div>
                </div>
                <span className="chart-lbl">{bar.sem}</span>
              </div>
            ))}
          </div>
          <div className="chart-legend">
            <span className="cl-dot cl-dot--active"></span><span className="cl-text">Current sem</span>
            <span className="cl-dot"></span><span className="cl-text">Previous</span>
          </div>
        </div>
      </div>
    </div>
  )
}

export default StudentDashboard

// frontend/src/views/student/StudentDashboard.vue
<template>
  <div class="dashboard-home">
    <div class="hero-banner">
      <div class="hero-bg-shape shape-1"></div>
      <div class="hero-bg-shape shape-2"></div>
      <div class="hero-body">

        <div v-if="profileIncomplete" class="profile-warning-banner">
          <div class="warning-content">
            <svg viewBox="0 0 24 24" fill="none" class="warning-icon"><path d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
            <div class="warning-text">
              <h4>Your profile is incomplete!</h4>
              <p>Please provide your contact details to complete your registration.</p>
            </div>
          </div>
          <router-link to="/student/profile" class="complete-btn">Complete Profile</router-link>
        </div>

        <div class="hero-left">
          <p class="hero-eyebrow"><span class="eyebrow-dot"></span>Academic Year 2026-2027 · 2nd Semester</p>
          <h2 class="hero-greeting">Good morning, {{ authStore.user?.name?.split(' ')[0] ?? 'Student' }} 👋</h2>
          <p class="hero-desc">Your current GWA is <strong>{{ studentProfile.gwa || '0.00' }}</strong>. You have <strong>{{ todaySchedule.length }} classes</strong> scheduled today.</p>
          <div class="hero-actions">
            <router-link to="/student/schedule" class="hero-btn-primary">
              <svg viewBox="0 0 18 18" fill="none" style="width:14px;height:14px"><rect x="2" y="3" width="14" height="13" rx="2" stroke="currentColor" stroke-width="1.4"/><path d="M6 1v4M12 1v4M2 7h14" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"/></svg>
              View Schedule
            </router-link>
            <router-link to="/student/academic-history" class="hero-btn-ghost">Academic History</router-link>
          </div>
        </div>

        <div class="hero-right">
          <div class="hero-stat-card"><span class="hsc-label">Current GWA</span><span class="hsc-value">{{ studentProfile.gwa || '0.00' }}</span><span class="hsc-sub">This semester</span></div>
          <div class="hero-stat-card accent"><span class="hsc-label">Activities</span><span class="hsc-value">{{ studentActivities.length }}</span><span class="hsc-sub">Non-academic</span></div>
        </div>

      </div>
    </div>

    <div class="stats-grid">
      <div class="stat-card" v-for="stat in stats" :key="stat.label"
        @click="stat.route && $router.push(stat.route)"
        :class="{ clickable: stat.route }">
        <div class="stat-top">
          <span class="stat-label">{{ stat.label }}</span>
          <div class="stat-icon" :style="{ background: stat.iconBg, color: stat.iconColor }">
            <component :is="'svg'" viewBox="0 0 18 18" fill="none" v-html="stat.iconPath"></component>
          </div>
        </div>
        <div class="stat-bottom">
          <span class="stat-value">{{ stat.value }}</span>
          <span class="stat-delta" :class="stat.deltaClass">{{ stat.delta }}</span>
        </div>
        <div class="stat-bar"><div class="stat-bar-fill" :style="{ width: stat.fill, background: stat.iconColor }"></div></div>
      </div>
    </div>

    <div class="bottom-grid">
      <div class="card">
        <div class="card-header">
          <div><h3 class="card-title">Today's Schedule</h3><p class="card-sub">{{ todayLabel }}</p></div>
          <router-link to="/student/schedule" class="card-link">View all →</router-link>
        </div>
        <div class="schedule-list">
          <div class="schedule-row" v-for="cls in todaySchedule" :key="cls.subject">
            <div class="schedule-time-col">
              <span class="schedule-time">{{ cls.time }}</span>
              <span class="schedule-duration">{{ cls.duration }}</span>
            </div>
            <div class="schedule-dot-col">
              <div class="schedule-dot" :style="{ background: cls.color }"></div>
              <div class="schedule-line"></div>
            </div>
            <div class="schedule-info">
              <p class="schedule-subject">{{ cls.subject }}</p>
              <p class="schedule-prof">{{ cls.professor }} · {{ cls.room }}</p>
            </div>
            <span class="schedule-type-badge" :style="{ background: cls.color + '20', color: cls.color }">{{ cls.type }}</span>
          </div>
          <div v-if="todaySchedule.length === 0" class="empty-small">No classes today.</div>
        </div>
      </div>

      <div class="card">
        <div class="card-header">
          <div><h3 class="card-title">Awards & Recognition</h3><p class="card-sub">Your achievements this year</p></div>
          <router-link to="/student/awards" class="card-link">View all →</router-link>
        </div>
        <div class="student-list">
          <div class="student-row" v-for="award in studentAwards.slice(0,3)" :key="award.title">
            <div class="student-avatar" :style="{ background: award.color }">
              <svg viewBox="0 0 14 14" fill="none" style="width:12px;height:12px"><path d="M7 1l1.5 4H13l-3.5 2.5 1.5 4L7 9.5 3.5 12l1.5-4L1 5h4.5L7 1z" stroke="currentColor" stroke-width="1.2" stroke-linejoin="round"/></svg>
            </div>
            <div class="student-info"><p class="student-name">{{ award.title }}</p><p class="student-course">{{ award.semester }}</p></div>
            <span class="student-tag tag-green">{{ award.badge }}</span>
          </div>
          <div v-if="studentAwards.length === 0" class="empty-small">No awards yet.</div>
        </div>
        <div class="violations-mini">
          <div class="vm-header">
            <span class="vm-label">Violations</span>
            <router-link to="/student/violations" class="card-link">See all →</router-link>
          </div>
          <div v-if="studentViolations.length === 0" class="vm-clear">
            <svg viewBox="0 0 16 16" fill="none" style="width:13px;height:13px"><circle cx="8" cy="8" r="6" stroke="#10b981" stroke-width="1.4"/><path d="M5 8l2 2 4-4" stroke="#10b981" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/></svg>
            No active violations. Keep it up!
          </div>
        </div>
      </div>

      <div class="card chart-card">
        <div class="card-header">
          <div><h3 class="card-title">Academic Performance</h3><p class="card-sub">GWA trend per semester</p></div>
          <router-link to="/student/academic-history" class="card-link">History →</router-link>
        </div>
        <div class="chart-bars">
          <div class="chart-bar-col" v-for="(bar, i) in studentChartData" :key="i">
            <div class="chart-bar-wrap">
              <div class="chart-bar-fill" :class="{ current: i === studentChartData.length - 1 }" :style="{ height: bar.pct + '%' }">
                <span class="chart-tooltip">{{ bar.sem }}: {{ bar.gwa }}</span>
              </div>
            </div>
            <span class="chart-bar-label">{{ bar.sem }}</span>
          </div>
        </div>
        <div class="chart-legend">
          <span class="legend-dot current"></span><span class="legend-text">Current sem</span>
          <span class="legend-dot"></span><span class="legend-text">Previous</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useAuthStore } from '../../store/auth'
import axios from 'axios'

const authStore = useAuthStore()
const stats = ref([])
const profileIncomplete = ref(false)
const studentProfile = ref({ gwa: '' })
const studentActivities = ref([
  { title: 'ICPEP.SE Hackathon' },
  { title: 'Annual JS Summit 2026' },
  { title: 'Campus Clean Drive' }
])
const studentAwards = ref([
  { title: "Dean's List Awardee", semester: '1st Sem 2025-2026', badge: 'Academic', color: '#f59e0b' },
  { title: 'Best Research Paper', semester: '2nd Sem 2024-2025', badge: 'Research', color: '#3b82f6' },
  { title: 'Outstanding Student Leader', semester: '1st Sem 2024-2025', badge: 'Leadership', color: '#10b981' }
])
const studentViolations = ref([])
const todaySchedule = ref([])
const studentChartData = ref([
  { sem: "1st '23", gwa: 1.95, pct: 45 }, { sem: "2nd '23", gwa: 1.88, pct: 55 },
  { sem: "1st '24", gwa: 1.81, pct: 68 }, { sem: "2nd '24", gwa: 1.77, pct: 76 },
  { sem: "1st '25", gwa: 1.74, pct: 83 }, { sem: "2nd '25", gwa: 1.72, pct: 90 }
])

const todayLabel = computed(() => new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }))

onMounted(async () => {
  try {
    const response = await axios.get('/student/profile')
    const s = response.data
    profileIncomplete.value = !s.gender || !s.contact_number || !s.address
    studentProfile.value = { ...s }
    stats.value = [
      { label: 'My GWA', value: s.gwa || '0.00', delta: 'Academic', deltaClass: 'positive', fill: '80%', iconBg: '#f5f3ff', iconColor: '#8b5cf6', route: '/student/academic-history', iconPath: '<path d="M2 13l3-5 3 3 3-4 5 6H2z" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>' },
      { label: 'Subjects', value: '7', delta: 'Enrolled', deltaClass: 'positive', fill: '70%', iconBg: '#eff6ff', iconColor: '#3b82f6', route: '/student/schedule', iconPath: '<rect x="2" y="2" width="14" height="14" rx="2" stroke="currentColor" stroke-width="1.4"/><path d="M6 6h6M6 9h4" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"/>' },
      { label: 'Awards', value: '3', delta: 'This year', deltaClass: 'positive', fill: '60%', iconBg: '#fffbeb', iconColor: '#f59e0b', route: '/student/awards', iconPath: '<path d="M9 1.5l1.6 4.8H16l-4.2 3.1 1.6 4.9L9 11.1l-4.4 3.2 1.6-4.9L2 7.3h5.4L9 1.5z" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>' },
      { label: 'Violations', value: '0', delta: 'Clear record', deltaClass: 'positive', fill: '0%', iconBg: '#fff1f2', iconColor: '#ef4444', route: '/student/violations', iconPath: '<path d="M9 5v4M9 11.5v.5M2.5 14h13a1 1 0 00.87-1.5L10 2.5a1 1 0 00-1.74 0L2.5 12.5A1 1 0 002.5 14z" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"/>' },
      { label: 'Activities', value: '6', delta: 'Non-academic', deltaClass: 'positive', fill: '50%', iconBg: '#fff5ef', iconColor: '#FF6B1A', route: '/student/activities', iconPath: '<circle cx="9" cy="5" r="3" stroke="currentColor" stroke-width="1.4"/><path d="M2 16c0-4 3-6 7-6s7 2 7 6" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"/>' }
    ]
  } catch (err) {
    console.error('Failed to fetch student profile:', err)
  }
})
</script>

<style scoped>
.dashboard-home { display: flex; flex-direction: column; gap: 0; }
.hero-banner { background: linear-gradient(130deg, #1a0a00 0%, #3d1500 55%, #FF6B1A 130%); border-radius: 20px; padding: 28px 32px; position: relative; overflow: hidden; margin-bottom: 20px; }
.profile-warning-banner { background: rgba(255,255,255,0.1); backdrop-filter: blur(10px); border: 1px solid rgba(255,255,255,0.2); border-radius: 16px; padding: 16px 24px; display: flex; align-items: center; justify-content: space-between; margin-bottom: 24px; gap: 20px; }
.warning-content { display: flex; align-items: center; gap: 16px; }
.warning-icon { width: 32px; height: 32px; color: #FF6B1A; }
.warning-text h4 { color: #fff; font-family: 'Syne', sans-serif; font-size: 16px; margin-bottom: 2px; }
.warning-text p { color: rgba(255,255,255,0.6); font-size: 13px; }
.complete-btn { background: #fff; color: #1a0a00; text-decoration: none; padding: 10px 20px; border-radius: 10px; font-size: 13px; font-weight: 700; transition: all 0.2s; white-space: nowrap; }
.complete-btn:hover { background: #FF6B1A; color: #fff; }
.hero-bg-shape { position: absolute; border-radius: 50%; pointer-events: none; }
.shape-1 { width: 320px; height: 320px; background: rgba(255,107,26,0.15); top: -100px; right: -80px; filter: blur(60px); }
.shape-2 { width: 200px; height: 200px; background: rgba(255,255,255,0.05); bottom: -60px; left: 40%; filter: blur(40px); }
.hero-body { position: relative; display: flex; align-items: center; justify-content: space-between; gap: 24px; }
.hero-eyebrow { display: flex; align-items: center; gap: 7px; font-size: 11px; color: rgba(255,255,255,0.45); text-transform: uppercase; letter-spacing: 0.8px; margin-bottom: 10px; }
.eyebrow-dot { width: 6px; height: 6px; background: #FF6B1A; border-radius: 50%; box-shadow: 0 0 8px #FF6B1A; }
.hero-greeting { font-family: 'Syne', sans-serif; font-size: 26px; font-weight: 700; color: #fff; letter-spacing: -0.5px; margin-bottom: 8px; }
.hero-desc { font-size: 13.5px; color: rgba(255,255,255,0.55); line-height: 1.6; max-width: 400px; margin-bottom: 20px; }
.hero-desc strong { color: rgba(255,255,255,0.85); font-weight: 500; }
.hero-actions { display: flex; gap: 10px; }
.hero-btn-primary { display: flex; align-items: center; gap: 8px; background: #FF6B1A; color: #fff; border: none; border-radius: 10px; padding: 10px 18px; font-size: 13px; font-weight: 600; font-family: 'DM Sans', sans-serif; cursor: pointer; transition: all 0.15s; box-shadow: 0 4px 16px rgba(255,107,26,0.4); text-decoration: none; }
.hero-btn-primary:hover { background: #e85500; transform: translateY(-1px); }
.hero-btn-ghost { background: rgba(255,255,255,0.1); color: rgba(255,255,255,0.8); border: 1px solid rgba(255,255,255,0.15); border-radius: 10px; padding: 10px 18px; font-size: 13px; font-weight: 500; font-family: 'DM Sans', sans-serif; cursor: pointer; transition: all 0.15s; backdrop-filter: blur(8px); text-decoration: none; }
.hero-btn-ghost:hover { background: rgba(255,255,255,0.18); }
.hero-right { display: flex; gap: 12px; flex-shrink: 0; }
.hero-stat-card { background: rgba(255,255,255,0.08); border: 1px solid rgba(255,255,255,0.12); border-radius: 14px; padding: 16px 20px; display: flex; flex-direction: column; gap: 2px; backdrop-filter: blur(8px); min-width: 100px; }
.hero-stat-card.accent { background: rgba(255,107,26,0.2); border-color: rgba(255,107,26,0.3); }
.hsc-label { font-size: 10px; color: rgba(255,255,255,0.4); text-transform: uppercase; letter-spacing: 0.6px; }
.hsc-value { font-family: 'Syne', sans-serif; font-size: 28px; font-weight: 800; color: #fff; line-height: 1; margin-top: 4px; }
.hsc-sub { font-size: 10px; color: rgba(255,255,255,0.4); margin-top: 2px; }
.stats-grid { display: grid; grid-template-columns: repeat(5, 1fr); gap: 14px; margin-top: 20px; }
.stat-card { background: #fff; border: 1px solid #f0e8e0; border-radius: 16px; padding: 18px 18px 14px; transition: all 0.2s; }
.stat-card.clickable { cursor: pointer; }
.stat-card.clickable:hover { border-color: #FF6B1A; transform: translateY(-2px); box-shadow: 0 8px 24px rgba(255,107,26,0.1); }
.stat-top { display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 14px; }
.stat-label { font-size: 10px; font-weight: 600; color: #9a8070; text-transform: uppercase; letter-spacing: 0.6px; line-height: 1.4; max-width: 80px; }
.stat-icon { width: 34px; height: 34px; border-radius: 9px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
.stat-icon svg { width: 16px; height: 16px; }
.stat-bottom { display: flex; align-items: flex-end; justify-content: space-between; gap: 4px; margin-bottom: 12px; }
.stat-value { font-family: 'Syne', sans-serif; font-size: 28px; font-weight: 800; color: #1a0a00; line-height: 1; }
.stat-delta { font-size: 10px; font-weight: 600; padding: 2px 6px; border-radius: 5px; white-space: nowrap; }
.stat-delta.positive { background: #f0fdf4; color: #16a34a; }
.stat-delta.negative { background: #fff1f2; color: #e11d48; }
.stat-delta.warning { background: #fff5ef; color: #c94000; }
.stat-bar { height: 3px; background: #f0e8e0; border-radius: 2px; overflow: hidden; }
.stat-bar-fill { height: 100%; border-radius: 2px; transition: width 1s ease; }
.bottom-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 16px; margin-top: 20px; }
.card { background: #fff; border: 1px solid #f0e8e0; border-radius: 18px; padding: 22px; }
.card-header { display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 20px; }
.card-title { font-family: 'Syne', sans-serif; font-size: 14px; font-weight: 700; color: #1a0a00; }
.card-sub { font-size: 11px; color: #b89f90; margin-top: 3px; }
.card-link { font-size: 11px; font-weight: 600; color: #FF6B1A; text-decoration: none; white-space: nowrap; background: none; border: none; cursor: pointer; font-family: 'DM Sans', sans-serif; }
.card-link:hover { text-decoration: underline; }
.chart-bars { display: flex; align-items: flex-end; gap: 8px; height: 140px; padding-bottom: 4px; }
.chart-bar-col { flex: 1; display: flex; flex-direction: column; align-items: center; height: 100%; gap: 4px; }
.chart-bar-wrap { flex: 1; width: 100%; display: flex; align-items: flex-end; }
.chart-bar-fill { width: 100%; background: #fde8d8; border-radius: 5px 5px 0 0; transition: height 0.8s ease; position: relative; cursor: pointer; }
.chart-bar-fill.current { background: #FF6B1A; }
.chart-bar-fill:hover .chart-tooltip { opacity: 1; transform: translateX(-50%) translateY(0); }
.chart-tooltip { position: absolute; bottom: calc(100% + 6px); left: 50%; transform: translateX(-50%) translateY(4px); background: #1a0a00; color: #fff; font-size: 10px; padding: 4px 8px; border-radius: 6px; white-space: nowrap; opacity: 0; transition: all 0.15s; pointer-events: none; }
.chart-bar-label { font-size: 8px; color: #b89f90; text-transform: uppercase; letter-spacing: 0.3px; text-align: center; white-space: nowrap; }
.chart-legend { display: flex; align-items: center; gap: 16px; margin-top: 16px; }
.legend-dot { width: 8px; height: 8px; border-radius: 50%; background: #fde8d8; }
.legend-dot.current { background: #FF6B1A; }
.legend-text { font-size: 10px; color: #b89f90; }
.student-list { display: flex; flex-direction: column; gap: 10px; }
.student-row { display: flex; align-items: center; gap: 10px; padding: 8px; border-radius: 10px; transition: background 0.15s; }
.student-row:hover { background: #faf8f6; }
.student-avatar { width: 32px; height: 32px; border-radius: 9px; display: flex; align-items: center; justify-content: center; font-size: 12px; font-weight: 700; color: #fff; flex-shrink: 0; }
.student-info { flex: 1; min-width: 0; }
.student-name { font-size: 12px; font-weight: 600; color: #1a0a00; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.student-course { font-size: 10px; color: #b89f90; }
.student-tag { font-size: 9px; font-weight: 700; padding: 2px 7px; border-radius: 5px; white-space: nowrap; }
.tag-green { background: #f0fdf4; color: #16a34a; }
.schedule-list { display: flex; flex-direction: column; }
.schedule-row { display: flex; align-items: flex-start; gap: 10px; padding: 10px 0; }
.schedule-time-col { width: 64px; flex-shrink: 0; }
.schedule-time { display: block; font-size: 11px; font-weight: 700; color: #1a0a00; }
.schedule-duration { font-size: 9px; color: #b89f90; }
.schedule-dot-col { display: flex; flex-direction: column; align-items: center; width: 18px; flex-shrink: 0; padding-top: 3px; }
.schedule-dot { width: 10px; height: 10px; border-radius: 50%; flex-shrink: 0; }
.schedule-line { flex: 1; width: 2px; background: #f0e8e0; margin-top: 4px; min-height: 20px; }
.schedule-row:last-child .schedule-line { display: none; }
.schedule-info { flex: 1; min-width: 0; }
.schedule-subject { font-size: 12px; font-weight: 600; color: #1a0a00; }
.schedule-prof { font-size: 10px; color: #b89f90; margin-top: 2px; }
.schedule-type-badge { font-size: 9px; font-weight: 700; padding: 2px 7px; border-radius: 5px; white-space: nowrap; align-self: flex-start; margin-top: 3px; }
.violations-mini { border-top: 1px solid #f0e8e0; padding-top: 14px; margin-top: 10px; }
.vm-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 10px; }
.vm-label { font-size: 11px; font-weight: 700; color: #1a0a00; text-transform: uppercase; letter-spacing: 0.5px; }
.vm-clear { display: flex; align-items: center; gap: 7px; font-size: 12px; color: #10b981; font-weight: 500; }
.empty-small { font-size: 12px; color: #b89f90; font-style: italic; padding: 8px 0; }
</style>
